name: weather_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  core_dependency:
    path: ./modules/core/core_dependency
  core_data:
    path: ./modules/core/core_data
  core_ui:
    path: ./modules/core/core_ui
  core_router:
    path: ./modules/core/core_router

  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: any
  injectable_generator: any
  retrofit_generator: any
  json_serializable: any
  freezed: ^2.4.5


flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/icons/

