name: core_dependency
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  injectable: ^2.1.1
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  dio: ^5.1.2
  retrofit: ^4.0.1
  equatable: ^2.0.5
  envied: ^0.3.0+3
  hive: ^2.2.3
  path_provider: ^2.0.15
  pretty_dio_logger: ^1.3.1
  freezed_annotation: ^2.2.0
  flutter_bloc: ^8.1.3
  rxdart: ^0.27.7
  shared_preferences: ^2.0.18
  phosphor_flutter: 2.0.0
  flutter_svg: ^2.0.7
  modal_bottom_sheet: 3.0.0-pre


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
